[tox]
isolated_build = true
envlist = py311, ruff, mypy, black

[testenv]
runner = uv-venv-lock-runner
allowlist_externals = sh
basepython = python3.11
commands =
  pytest --basetemp={envtmpdir} \
    -c {toxinidir}/pyproject.toml \
    --cov=erp_api

[testenv:ruff]
commands = ruff check .

[testenv:mypy]
commands = mypy --config-file {toxinidir}/pyproject.toml .

[testenv:black]
commands = black --config {toxinidir}/pyproject.toml --check .
